version: '3'

services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"

    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    networks:
      - postgresql
networks:
  postgresql:
    driver: bridge
